from pydantic import BaseModel, Field
from typing import Optional

# MONGODB
class User(BaseModel):
    # id_user is generated by MongoDB
    full_name: str
    email: str
    username: str
    password: str
    salt: str
    is_active: bool
    last_seen: str

class ChatGroup(BaseModel):
    # id_chat is _id from MongoDB
    is_group: bool = True
    name: str
    admin: str
    members: list # + unread_messages, last_message(date, content, sender)

class ChatUser(BaseModel):
    # id_chat is _id from MongoDB
    is_group: bool = False
    members: list # + unread_messages, last_message(date, content, sender)

class Message(BaseModel):
    # id_message is _id from MongoDB
    id_group: str
    sender: str
    content: str
    date: str
